version: "3.7"
services:
  mongo-db:
    container_name: mongodb
    image:  mongo:4.2
    restart:  always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mongo_2439
  app:
    container_name: vidly
    build:  .
    ports:
      - 3000:3001
    environment:
      - NODE_ENV=test
    depends_on: 
      - mongo-db
  # mongo-express:
  #   container_name: mongo_express
  #   image:  mongo-express:0.54.0
  #   ports:
  #     - 8080:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo_2439
  #     - ME_CONFIG_MONGODB_SERVER=mongo-db
  #   depends_on:
  #     - mongo-db
    
